version: '3.7'

services:

  ui-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4455:4435"
    command:
      ory-poc
    networks:
      - intranet

  hydra:
    image: oryd/hydra:v1.10.6
    depends_on:
      - hydra-migrate
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    restart: on-failure # TODO figure out why we need this (incorporate health check into hydra migrate command?)
    environment:
      - LOG_LEAK_SENSITIVE_VALUES=true
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_SELF_PUBLIC=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:4455/auth/consent
      - URLS_LOGIN=http://127.0.0.1:4455/auth/login
      - URLS_LOGOUT=http://127.0.0.1:4455/logout
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
      - DSN=postgres://hydra:secret@postgres_hydra:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v1.10.6
    environment:
      - DSN=postgres://hydra:secret@postgres_hydra:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  # Database for Hydra
  postgres_hydra:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet

networks:
  intranet: