# Configuration of access rules
# Docs: https://www.ory.sh/oathkeeper/docs/api-access-rules
#
# In this project I do not tend to build Authorization layer
# so all authorizer handlers are "allow".

- id: "ory:kratos:public:browser"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /.ory/kratos/public
  match:
    url: "http://127.0.0.1:4455/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /.ory/kratos/public
  match:
    url: "http://oathkeeper:4455/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "ory:hydra:public:browser"
  upstream:
    preserve_host: true
    url: "http://hydra:4444"
    strip_path: /.ory/hydra/public
  match:
    url: "http://127.0.0.1:4455/.ory/hydra/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "ory:hydra:public"
  upstream:
    preserve_host: true
    url: "http://hydra:4444"
    strip_path: /.ory/kratos/public
  match:
    url: "http://oathkeeper:4455/.ory/hydra/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "ory:authctl:anonymous"
  upstream:
    preserve_host: true
    url: "http://authctl:4435"
  match:
    url: "http://127.0.0.1:4455/<{error,recovery,verify,auth/*,auth/hydra/*,**.css,**.js}>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

# Protect APIS that match the config url
# request will be authenticated using cookie_session authenticator.
- id: "ory:authctl:protected"
  upstream:
    preserve_host: true
    url: "http://authctl:4435"
  match:
    url: "http://127.0.0.1:4455/<{debug,dashboard,settings}>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4455/auth/login

- id: "ory:ui:callback"
  upstream:
    preserve_host: true
    url: "http://ui:4436"
  match:
    url: "http://127.0.0.1:4455/<{callback}>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "ory:ui:public"
  upstream:
    preserve_host: true
    url: "http://ui:4436"
  match:
    url: "http://127.0.0.1:4455/<{/,}>"
    methods:
      - GET
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "ory:mock-api:protected"
  upstream:
    preserve_host: true
    url: "http://api:4437"
  match:
    url: "http://127.0.0.1:4455/<{mock/api}>"
    methods:
      - GET
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
#    - handler: noop
    - handler: id_token
    - handler: header
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4455/auth/login

- id: "ory:api:protected"
  upstream:
    preserve_host: true
    url: "http://authctl:4435"
  match:
    url: "http://127.0.0.1:4455/<{user/change-password}>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    #    - handler: noop
    - handler: id_token
    - handler: header
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4455/auth/login
